import os
from dotenv import load_dotenv

load_dotenv()


DATABASE_URL = os.getenv('DATABASE_URL')
SECRET_KEY = os.getenv('SECRET_KEY')

ALGORITHM = 'HS256'
ACCESS_TOKEN_EXPIRE_MINUTES = 60
# ACCESS_TOKEN_EXPIRE_MINUTES = 0.2
REFRESH_TOKEN_EXPIRE_DAYS = 1
